
# date format: 'YYYY-MM-DD'
start: '2015-05-01'
end: '2016-10-31'
path: 39  
row: 27
latitude:
longitude:
output_path: /path/to/images/landsat
satellite: LC8
usgs_creds: /path/to/usgs.txt
return_list: False
zipped: False
max_cloud_percent: 100
