# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
@EXPLICIT
https://conda.anaconda.org/conda-forge/linux-64/affine-2.0.0.post1-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/asn1crypto-0.22.0-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/bkcharts-0.2-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/bokeh-0.12.6-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/boto3-1.4.4-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/botocore-1.5.55-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/bottleneck-1.2.0-np112py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/ca-certificates-2017.4.17-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/certifi-2017.4.17-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/cffi-1.10.0-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/chardet-3.0.2-py35_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/click-6.7-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/click-plugins-1.0.3-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/cligj-0.4.0-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/cloudpickle-0.3.1-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/cryptography-1.8.1-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/curl-7.52.1-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/cycler-0.10.0-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/dask-0.15.0-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/dbus-1.10.10-3.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/distributed-1.17.1-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/docutils-0.13.1-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/expat-2.1.0-2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/fiona-1.7.8-np112py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/fontconfig-2.12.1-4.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/freetype-2.7-1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/freexl-1.0.2-1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/future-0.16.0-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/gdal-2.2.0-np112py35_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/geos-3.5.1-1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/gettext-0.19.7-1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/giflib-5.1.4-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/glib-2.51.4-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/gst-plugins-base-1.8.0-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/gstreamer-1.8.0-2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/h5netcdf-0.3.1-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/h5py-2.7.0-np112py35_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/hdf4-4.2.12-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/hdf5-1.8.18-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/heapdict-1.0.0-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/httplib2-0.10.3-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/icu-58.1-1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/idna-2.5-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/jinja2-2.9.5-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/jmespath-0.9.2-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/jpeg-9b-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/json-c-0.12-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/kealib-1.4.7-2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/krb5-1.14.2-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libdap4-3.18.3-2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libffi-3.2.1-3.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/libgfortran-3.0.0-1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libiconv-1.14-4.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libnetcdf-4.4.1.1-5.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libpng-1.6.28-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libpq-9.5.4-4.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libspatialite-4.3.0a-15.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libtiff-4.0.6-7.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libxcb-1.12-1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libxml2-2.9.4-4.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/llvmlite-0.18.0-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/locket-0.2.0-py35_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/markupsafe-1.0-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/matplotlib-2.0.2-np112py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/mkl-2017.0.1-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/msgpack-python-0.4.8-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/munch-2.1.1-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/ncurses-5.9-10.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/netcdf4-1.2.9-np112py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/numba-0.33.0-np112py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/numpy-1.12.1-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/openjpeg-2.1.2-3.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/openssl-1.0.2k-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/packaging-16.8-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pandas-0.20.2-np112py35_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/partd-0.3.8-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pcre-8.39-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pip-9.0.1-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/proj4-4.9.3-3.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/psutil-5.2.1-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pycparser-2.17-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pyopenssl-16.2.0-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pyparsing-2.2.0-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pyproj-1.9.5.1-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pyqt-5.6.0-py35_4.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pysocks-1.6.7-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/python-3.5.3-3.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/python-dateutil-2.6.0-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pytz-2017.2-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pyyaml-3.12-py35_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/qt-5.6.2-3.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/rasterio-1.0a9-np112py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/readline-6.2-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/requests-2.18.1-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/s3transfer-0.1.10-py35_1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/scipy-0.19.0-np112py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/selenium-3.4.3-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/setuptools-33.1.1-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/shapely-1.5.17-np112py35_3.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/sip-4.18-py35_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/six-1.10.0-py35_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/snuggs-1.4.1-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/sortedcontainers-1.5.3-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/sqlite-3.13.0-1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/tblib-1.3.2-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/tk-8.5.19-1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/toolz-0.8.2-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/tornado-4.5.1-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/urllib3-1.21.1-py35_1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/util-linux-2.21-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/wheel-0.29.0-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xarray-0.9.6-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xerces-c-3.1.4-3.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xlrd-1.0.0-py35_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-libxau-1.0.8-3.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-libxdmcp-1.1.2-3.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xz-5.2.2-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/yaml-0.1.6-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/zict-0.1.2-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/zlib-1.2.11-0.tar.bz2
