# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
@EXPLICIT
https://repo.continuum.io/pkgs/main/linux-64/ca-certificates-2018.03.07-0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/intel-openmp-2018.0.0-8.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/libgcc-ng-7.2.0-hdf63c60_3.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libgfortran-ng-7.2.0-hdf63c60_3.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/libstdcxx-ng-7.2.0-hdf63c60_3.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/poppler-data-0.4.8-hf2eda46_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/bzip2-1.0.6-h9a117a8_4.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/expat-2.2.5-he0dffb1_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/freexl-1.0.5-h14c3975_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/geos-3.6.2-heeff764_2.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/giflib-5.1.4-h26a3ec6_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/icu-58.2-h9c2bf20_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/jpeg-9b-h024ee3a_2.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/json-c-0.12.1-ha6a3662_2.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/libffi-3.2.1-hd88cf55_4.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libuuid-1.0.3-h1bed415_2.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libxcb-1.13-h1bed415_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/mkl-2018.0.2-1.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/ncurses-6.0-h9df7e31_2.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/openssl-1.0.2o-h20670df_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pcre-8.42-h439df22_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pixman-0.34.0-hceecf20_3.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/proj4-4.9.3-hc8507d1_7.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/tk-8.6.7-hc745277_3.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/xz-5.2.3-h5e939de_4.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/zlib-1.2.11-ha838bed_2.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/glib-2.53.6-h5d9569c_2.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/hdf4-4.2.13-h3ca952b_2.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/hdf5-1.10.1-h9caa474_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libboost-1.65.1-habcd387_4.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/libedit-3.1-heed3624_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libpng-1.6.34-hb9fc6fc_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libssh2-1.8.0-h9cfc8f7_4.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libtiff-4.0.9-h28f6b97_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libxml2-2.9.8-hf84eae3_0.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/readline-7.0-ha6073c6_4.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/xerces-c-3.2.1-hac72e42_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/freetype-2.8-hab7d2ae_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/kealib-1.4.7-h79811e5_5.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/krb5-1.16-h3f6afd0_6.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libcurl-7.59.0-h1ad7b7a_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libkml-1.3.0-h9d32c78_3.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/openjpeg-2.3.0-hef292c2_0.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/sqlite-3.23.1-he433501_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/curl-7.59.0-h84994c4_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/fontconfig-2.12.6-h49f89f6_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libpq-10.3-h1ad7b7a_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libspatialite-4.3.0a-h72746d6_18.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/python-3.6.5-hc3d631a_2.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/cairo-1.14.12-h77bcde2_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/certifi-2018.4.16-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/click-6.7-py36h5253387_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libdap4-3.19.0-h5bd89bb_2.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libnetcdf-4.4.1.1-h816af47_8.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pytz-2018.4-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/six-1.11.0-py36h372c433_1.tar.bz2
https://repo.anaconda.com/pkgs/free/linux-64/click-plugins-1.0.3-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/free/linux-64/cligj-0.4.0-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/munch-2.3.1-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/poppler-0.60.1-hc909a00_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/python-dateutil-2.7.2-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/setuptools-39.1.0-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libgdal-2.2.2-h804cdde_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/wheel-0.31.0-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pip-10.0.1-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/gdal-2.2.2-py36hc209d97_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/mkl_fft-1.0.1-py36h3010b51_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/mkl_random-1.0.1-py36h629b387_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/numpy-1.14.2-py36hdbf6ddf_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pandas-0.22.0-py36hf484d3e_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/shapely-1.6.4-py36h0c48222_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/fiona-1.7.10-py36h48a52f0_0.tar.bz2
